import type { CareerFieldMeta, CareerFieldId } from '../../src/types'

export const CAREER_FIELDS: Record<CareerFieldId, CareerFieldMeta> = {
  data_analytics: {
    id: 'data_analytics',
    name: 'Data Analytics',
    tagline: 'Transform Raw Data into Strategic Business Decisions',
    icon: '📊',
    color: 'from-blue-600 to-indigo-600',
    accentColor: '#3b82f6',
    avgSalary: '$85,000 - $130,000',
    description:
      'Master the end-to-end analytics stack from spreadsheet data manipulation and SQL database querying to Python transformation, statistical analysis, and interactive dashboarding in Power BI and Tableau.',
    jobRoles: ['Data Analyst', 'Business Intelligence Analyst', 'Operations Analyst', 'Marketing Analytics Specialist'],
    totalSkills: 8,
    skillsRoadmap: [
      {
        id: 'da-01',
        title: 'Advanced Excel & Spreadsheets',
        order: 1,
        estimatedHours: 12,
        description: 'Master VLOOKUP, INDEX/MATCH, Pivot Tables, dynamic formulas, and clean data modeling.',
        topics: ['Data Formatting', 'VLOOKUP & XLOOKUP', 'Pivot Tables & Charts', 'Conditional Logic & Functions'],
        theoryMarkdown: `### Excel for Data Analytics\nSpreadsheets remain the universal communication medium in business. Learn how to clean and pivot structured business data.`,
        keyTakeaways: ['Use XLOOKUP for robust relational lookups', 'Construct multi-dimensional Pivot Tables', 'Apply clean numerical formatting standards'],
        quiz: [
          {
            id: 'q-da-01',
            question: 'Which modern Excel function replaces both VLOOKUP and HLOOKUP with faster, bidirectional searches?',
            options: ['MATCH', 'INDEX', 'XLOOKUP', 'LOOKUP_EXACT'],
            correctOptionIndex: 2,
            explanation: 'XLOOKUP can search in any direction and handles missing values natively.'
          }
        ],
        practicePrompt: 'Design a dynamic sales dashboard utilizing Pivot Tables and slicers.'
      },
      {
        id: 'da-02',
        title: 'Relational Databases & SQL Querying',
        order: 2,
        estimatedHours: 18,
        description: 'Extract, filter, aggregate, and join complex multi-table databases using SQL.',
        topics: ['SELECT & WHERE Filtering', 'GROUP BY & Aggregations', 'INNER/LEFT/RIGHT JOINs', 'Window Functions & CTEs'],
        theoryMarkdown: `### SQL Mastery\nSQL is the foundation of data extraction. Master multi-table joins, subqueries, and window functions like ROW_NUMBER() and RANK().`,
        keyTakeaways: ['Filter high-volume records efficiently', 'Combine normalized schemas with JOINs', 'Calculate rolling metrics using OVER (PARTITION BY)'],
        quiz: [
          {
            id: 'q-da-02',
            question: 'Which clause is used to filter aggregated data generated by a GROUP BY statement?',
            options: ['WHERE', 'HAVING', 'FILTER', 'ORDER BY'],
            correctOptionIndex: 1,
            explanation: 'HAVING filters aggregated groups, whereas WHERE filters individual rows before grouping.'
          }
        ],
        practicePrompt: 'Write a query to calculate month-over-month revenue growth using a Common Table Expression.'
      },
      {
        id: 'da-03',
        title: 'Python for Data Analysis',
        order: 3,
        estimatedHours: 20,
        description: 'Use Python fundamentals, data structures, and scripting to automate data ingestion.',
        topics: ['Python Syntax & Lists', 'Dictionaries & Sets', 'Reading CSV/JSON files', 'Writing Reusable Functions'],
        theoryMarkdown: `### Python Scripting\nAutomate repetitive analytical workflows and build scalable pipelines.`,
        keyTakeaways: ['Parse structured JSON and tabular CSV data', 'Write defensive scripts with error handling', 'Structure reusable analytics modules'],
        quiz: [
          {
            id: 'q-da-03',
            question: 'Which built-in Python data structure stores key-value pairs with O(1) average lookup time?',
            options: ['List', 'Tuple', 'Dictionary', 'Array'],
            correctOptionIndex: 2,
            explanation: 'Dictionaries in Python are hash tables providing O(1) key lookups.'
          }
        ]
      },
      {
        id: 'da-04',
        title: 'Pandas & NumPy Data Wrangling',
        order: 4,
        estimatedHours: 25,
        description: 'Slice, transform, merge, and clean massive DataFrames with lightning-fast vectorized operations.',
        topics: ['Series & DataFrame Slicing', 'Vectorized NumPy Operations', 'Handling Nulls & Outliers', 'Grouping & Pivoting'],
        theoryMarkdown: `### Pandas Data Manipulation\nPandas is the workhorse of modern data processing in Python.`,
        keyTakeaways: ['Avoid Python for-loops by utilizing vectorized operations', 'Filter with boolean masking', 'Merge disparate tables seamlessly'],
        quiz: [
          {
            id: 'q-da-04',
            question: 'Which Pandas method is best suited to fill missing NaN values with the median of a column?',
            options: ['df.dropna()', 'df.fillna(df.median())', 'df.replace_null()', 'df.clean()'],
            correctOptionIndex: 1,
            explanation: 'fillna() imputes missing values with computed summary statistics.'
          }
        ]
      },
      {
        id: 'da-05',
        title: 'Applied Business Statistics',
        order: 5,
        estimatedHours: 15,
        description: 'Understand distributions, variance, hypothesis testing, correlation, and A/B test analysis.',
        topics: ['Mean, Median, Standard Deviation', 'Normal & Skewed Distributions', 'Correlation vs Causation', 'Hypothesis Testing & p-values'],
        theoryMarkdown: `### Statistical Rigor\nDistinguish meaningful business insights from random noise using statistical hypothesis testing.`,
        keyTakeaways: ['Calculate confidence intervals', 'Interpret p-values correctly', 'Avoid spurious correlations'],
        quiz: [
          {
            id: 'q-da-05',
            question: 'What does a p-value less than 0.05 typically signify in standard hypothesis testing?',
            options: ['The null hypothesis is true', 'Statistically significant evidence against the null hypothesis', 'The sample size is too small', 'A calculation error occurred'],
            correctOptionIndex: 1,
            explanation: 'A p-value < 0.05 indicates the observed effect is unlikely under the null hypothesis.'
          }
        ]
      },
      {
        id: 'da-06',
        title: 'Data Cleaning & Validation',
        order: 6,
        estimatedHours: 14,
        description: 'Detect anomalies, type inconsistencies, deduplication, and schema validation.',
        topics: ['Deduplication', 'Regex Pattern Matching', 'Type Casting', 'Integrity Assertions'],
        theoryMarkdown: `### Clean Data Pipeline\nOver 70% of analytical effort is spent validating and sanitizing dirty incoming feeds.`,
        keyTakeaways: ['Normalize dates and currency formats', 'Identify multivariate outliers with IQR', 'Automate data quality assertions'],
        quiz: [
          {
            id: 'q-da-06',
            question: 'Which method uses the 1st and 3rd quartiles to identify numerical outliers?',
            options: ['Z-Score only', 'Interquartile Range (IQR)', 'Standard Error', 'Root Mean Square'],
            correctOptionIndex: 1,
            explanation: 'IQR = Q3 - Q1, with outliers typically defined beyond 1.5 * IQR.'
          }
        ]
      },
      {
        id: 'da-07',
        title: 'Data Storytelling & Visualization',
        order: 7,
        estimatedHours: 16,
        description: 'Design impactful visual charts with Matplotlib, Seaborn, and presentation principles.',
        topics: ['Chart Selection Strategy', 'Color Theory & Accessibility', 'Seaborn Heatmaps & Pairplots', 'Executive Slide Decks'],
        theoryMarkdown: `### Visual Communication\nTurn complex multivariate data into intuitive graphics that executives understand in 5 seconds.`,
        keyTakeaways: ['Pick bar charts for categorical comparison and line charts for temporal trends', 'Minimize cognitive load and declutter charts'],
        quiz: [
          {
            id: 'q-da-07',
            question: 'Which chart type is best suited to display the distribution and spread of continuous numerical data?',
            options: ['Pie Chart', 'Histogram / Box Plot', 'Radar Chart', 'Donut Chart'],
            correctOptionIndex: 1,
            explanation: 'Histograms and box plots clearly show distribution, skewness, and outliers.'
          }
        ]
      },
      {
        id: 'da-08',
        title: 'BI Tools: Power BI & Tableau Dashboards',
        order: 8,
        estimatedHours: 22,
        description: 'Build automated interactive enterprise dashboards with DAX measures and live SQL connections.',
        topics: ['DAX Calculations in Power BI', 'Tableau Calculated Fields', 'Drill-through Filtering', 'Publishing & Scheduled Refreshes'],
        theoryMarkdown: `### Enterprise Business Intelligence\nEmpower stakeholders with interactive self-serve dashboards.`,
        keyTakeaways: ['Write calculated measures in DAX', 'Establish Star Schema data models', 'Set up automated data gateway refreshes'],
        quiz: [
          {
            id: 'q-da-08',
            question: 'In Power BI, which formula language is used to create custom calculated measures and dynamic aggregations?',
            options: ['M Query', 'DAX (Data Analysis Expressions)', 'VBA', 'TypeScript'],
            correctOptionIndex: 1,
            explanation: 'DAX is used for calculations and aggregations in Power BI and Excel Power Pivot.'
          }
        ]
      }
    ]
  },
  web_dev: {
    id: 'web_dev',
    name: 'Full-Stack Web Development',
    tagline: 'Engineer Responsive Frontends and Scalable Web Backends',
    icon: '🌐',
    color: 'from-cyan-600 to-blue-600',
    accentColor: '#06b6d4',
    avgSalary: '$90,000 - $145,000',
    description:
      'Build end-to-end web applications with modern HTML/CSS, TypeScript, React components, state management, Node.js API servers, database architecture, and cloud deployment.',
    jobRoles: ['Frontend Engineer', 'Full-Stack Developer', 'Backend Node.js Engineer', 'React Developer'],
    totalSkills: 8,
    skillsRoadmap: [
      {
        id: 'wd-01',
        title: 'Modern HTML5 & Semantic Web',
        order: 1,
        estimatedHours: 10,
        description: 'Build accessible, semantic markup with modern HTML5 elements, SEO best practices, and forms.',
        topics: ['Semantic Elements', 'Accessible Forms', 'SEO Metadata', 'ARIA Roles'],
        theoryMarkdown: `### Semantic Web Structure\nStructure pages for humans, assistive technologies, and search engines.`,
        keyTakeaways: ['Use single h1 per page', 'Ensure proper label associations on inputs'],
        quiz: [
          {
            id: 'q-wd-01',
            question: 'Which HTML5 element is most appropriate for a self-contained composition intended to be reusable?',
            options: ['<div>', '<article>', '<section>', '<aside>'],
            correctOptionIndex: 1,
            explanation: '<article> represents an independent, self-contained piece of content.'
          }
        ]
      },
      {
        id: 'wd-02',
        title: 'CSS3, Flexbox, Grid & Modern Styling',
        order: 2,
        estimatedHours: 18,
        description: 'Master Flexbox layouts, 2D CSS Grid, CSS Variables, transitions, and responsive mobile-first design.',
        topics: ['Flexbox 1D Layouts', 'CSS Grid 2D Positioning', 'Media Queries & Breakpoints', 'CSS Custom Properties'],
        theoryMarkdown: `### Modern Layout Engines\nBuild responsive layouts that seamlessly adapt from 320px mobile screens to 4K displays.`,
        keyTakeaways: ['Use Flexbox for single-axis alignment', 'Use Grid for complex 2D page architecture'],
        quiz: [
          {
            id: 'q-wd-02',
            question: 'Which CSS property creates a grid where columns automatically fit the available container width?',
            options: ['grid-template-columns: repeat(auto-fit, minmax(200px, 1fr))', 'display: flex', 'grid-auto-flow: dense', 'float: left'],
            correctOptionIndex: 0,
            explanation: 'repeat(auto-fit, minmax(...)) creates responsive fluid grids without media queries.'
          }
        ]
      },
      {
        id: 'wd-03',
        title: 'JavaScript ES6+ & Asynchronous Programming',
        order: 3,
        estimatedHours: 24,
        description: 'Master closures, event loop, Promises, async/await, array methods, and DOM manipulation.',
        topics: ['Arrow Functions & Destructuring', 'Promises & async/await', 'Array map/filter/reduce', 'Event Bubbling & Delegation'],
        theoryMarkdown: `### Asynchronous Core\nUnderstand the event loop, microtask queue, and asynchronous data fetching.`,
        keyTakeaways: ['Write declarative code with map/filter/reduce', 'Handle API responses gracefully with try/catch'],
        quiz: [
          {
            id: 'q-wd-03',
            question: 'What does Promise.all() do when one of the passed promises rejects?',
            options: ['Waits for the rest', 'Immediately rejects with that error', 'Returns undefined', 'Retries the promise'],
            correctOptionIndex: 1,
            explanation: 'Promise.all() short-circuits and immediately rejects if any promise fails.'
          }
        ]
      },
      {
        id: 'wd-04',
        title: 'TypeScript for Scalable Applications',
        order: 4,
        estimatedHours: 16,
        description: 'Add static typing, interfaces, generics, and union types to write maintainable codebases.',
        topics: ['Type Inference & Primitives', 'Interfaces & Types', 'Generics & Utility Types', 'Strict Null Checks'],
        theoryMarkdown: `### Type Safety\nCatch errors during development before they ever hit production.`,
        keyTakeaways: ['Leverage generics for reusable APIs', 'Use discriminated unions for state management'],
        quiz: [
          {
            id: 'q-wd-04',
            question: 'Which TypeScript utility type makes all properties of an interface optional?',
            options: ['Required<T>', 'Partial<T>', 'Readonly<T>', 'Record<K,T>'],
            correctOptionIndex: 1,
            explanation: 'Partial<T> transforms all properties of type T into optional fields.'
          }
        ]
      },
      {
        id: 'wd-05',
        title: 'React & Modern Component Architecture',
        order: 5,
        estimatedHours: 30,
        description: 'Master functional components, hooks (useState, useEffect, useMemo), custom hooks, and virtual DOM.',
        topics: ['JSX & Component Props', 'useState & useEffect Lifecycle', 'Context API & State Management', 'Performance Optimization'],
        theoryMarkdown: `### Declarative UI\nCompose complex reactive applications out of small, reusable components.`,
        keyTakeaways: ['Keep state minimal and derive values where possible', 'Memoize expensive computations with useMemo'],
        quiz: [
          {
            id: 'q-wd-05',
            question: 'What is the purpose of the dependency array in React useEffect?',
            options: ['Specifies component styles', 'Controls when the effect re-runs based on changed variables', 'Passes props to children', 'Initializes state'],
            correctOptionIndex: 1,
            explanation: 'useEffect only re-runs if one of the values in its dependency array changes.'
          }
        ]
      },
      {
        id: 'wd-06',
        title: 'Backend API Development with Node.js & Express',
        order: 6,
        estimatedHours: 25,
        description: 'Build RESTful APIs, middleware chains, error handling, authentication, and file handling.',
        topics: ['Express Routing & Controllers', 'Middleware Patterns', 'JWT Authentication & Cookies', 'Input Validation & Security'],
        theoryMarkdown: `### Server Architecture\nDesign robust, secure backend services that power client applications.`,
        keyTakeaways: ['Implement centralized error handling middleware', 'Sign and verify secure JWT session tokens'],
        quiz: [
          {
            id: 'q-wd-06',
            question: 'In Express middleware, what happens if you do not call next() or send a response?',
            options: ['Server crashes', 'Request hangs indefinitely', 'Client receives 200 OK', 'Route automatically finishes'],
            correctOptionIndex: 1,
            explanation: 'Express requires either calling next() to advance or sending a response to complete the HTTP cycle.'
          }
        ]
      },
      {
        id: 'wd-07',
        title: 'Databases: SQL & NoSQL Architecture',
        order: 7,
        estimatedHours: 20,
        description: 'Design normalized relational schemas (PostgreSQL / SQLite) and flexible document stores (MongoDB).',
        topics: ['Schema Design & Foreign Keys', 'Indexing & Query Optimization', 'Transactions & ACID Compliance', 'ORMs & Query Builders'],
        theoryMarkdown: `### Data Persistence\nStore user records securely with indexing, migrations, and transactional integrity.`,
        keyTakeaways: ['Index columns frequently queried in WHERE and JOIN clauses', 'Use transactions for atomic multi-step operations'],
        quiz: [
          {
            id: 'q-wd-07',
            question: 'What database mechanism ensures that a group of SQL operations either all succeed or all rollback?',
            options: ['Foreign Key', 'Database Index', 'ACID Transaction', 'Trigger'],
            correctOptionIndex: 2,
            explanation: 'Transactions guarantee Atomicity, Consistency, Isolation, and Durability.'
          }
        ]
      },
      {
        id: 'wd-08',
        title: 'Full-Stack Integration, Testing & Deployment',
        order: 8,
        estimatedHours: 25,
        description: 'Connect frontend to backend, write automated tests, configure CI/CD, and deploy to production.',
        topics: ['CORS & Environment Config', 'Unit & Integration Testing', 'Docker Basics', 'Vercel / Cloud Deployment'],
        theoryMarkdown: `### Production Readiness\nShip production-grade web applications with automated testing and continuous deployment.`,
        keyTakeaways: ['Isolate environment secrets with .env files', 'Set up automated CI testing before merging code'],
        quiz: [
          {
            id: 'q-wd-08',
            question: 'Which HTTP header prevents unauthorized cross-origin requests from browser clients?',
            options: ['Content-Type', 'Access-Control-Allow-Origin (CORS)', 'Authorization', 'Cache-Control'],
            correctOptionIndex: 1,
            explanation: 'CORS headers instruct the browser on which origins are permitted to access server resources.'
          }
        ]
      }
    ]
  },
  ai_ml: {
    id: 'ai_ml',
    name: 'Artificial Intelligence & Machine Learning',
    tagline: 'Build Predictive Models, Neural Networks & Generative AI Systems',
    icon: '🤖',
    color: 'from-purple-600 to-indigo-600',
    accentColor: '#8b5cf6',
    avgSalary: '$110,000 - $175,000',
    description:
      'From foundational mathematics and Scikit-Learn algorithms to Deep Learning with PyTorch, Computer Vision, Natural Language Processing, and deploying Large Language Model applications.',
    jobRoles: ['Machine Learning Engineer', 'AI Research Specialist', 'Data Scientist', 'LLM Application Developer'],
    totalSkills: 7,
    skillsRoadmap: [
      {
        id: 'ai-01',
        title: 'Mathematics for Machine Learning',
        order: 1,
        estimatedHours: 18,
        description: 'Linear algebra (matrices, eigenvalues), calculus (gradients), and probability distributions.',
        topics: ['Matrix Multiplication & Vectors', 'Partial Derivatives & Chain Rule', 'Probability & Bayes Rule', 'Optimization Functions'],
        theoryMarkdown: `### Mathematical Foundations\nMachine learning is optimization over high-dimensional vector spaces.`,
        keyTakeaways: ['Understand gradient descent geometrically', 'Master matrix transformations for data embeddings'],
        quiz: [
          {
            id: 'q-ai-01',
            question: 'What mathematical vector points in the direction of the steepest rate of increase of a function?',
            options: ['Hessian', 'Gradient', 'Jacobian', 'Eigenvector'],
            correctOptionIndex: 1,
            explanation: 'The gradient vector contains partial derivatives and indicates steepest ascent.'
          }
        ]
      },
      {
        id: 'ai-02',
        title: 'Classical Machine Learning with Scikit-Learn',
        order: 2,
        estimatedHours: 24,
        description: 'Linear regression, logistic regression, decision trees, random forests, and gradient boosting.',
        topics: ['Supervised vs Unsupervised', 'Regression & Classification', 'Ensemble Models (Random Forest, XGBoost)', 'Overfitting & Regularization'],
        theoryMarkdown: `### Predictive Modeling\nSelect, train, and evaluate classical machine learning algorithms on structured datasets.`,
        keyTakeaways: ['Use cross-validation to prevent data leakage', 'Tune hyperparameters with Grid/Randomized search'],
        quiz: [
          {
            id: 'q-ai-02',
            question: 'Which technique combines multiple decision trees trained on random subsets of data to reduce variance?',
            options: ['Linear Regression', 'Random Forest', 'K-Means', 'PCA'],
            correctOptionIndex: 1,
            explanation: 'Random Forest is an ensemble bagging technique that averages predictions across multiple trees.'
          }
        ]
      },
      {
        id: 'ai-03',
        title: 'Model Evaluation & Feature Engineering',
        order: 3,
        estimatedHours: 16,
        description: 'Confusion matrices, ROC-AUC, precision/recall trade-offs, standardization, and PCA reduction.',
        topics: ['Precision, Recall & F1-Score', 'ROC & AUC Curves', 'StandardScaler vs MinMaxScaler', 'Feature Selection'],
        theoryMarkdown: `### Model Validation\nAccuracy is misleading on imbalanced datasets. Learn precision, recall, and ROC curves.`,
        keyTakeaways: ['Choose F1-Score for imbalanced classification', 'Scale numerical features before training distance-based models'],
        quiz: [
          {
            id: 'q-ai-03',
            question: 'In medical diagnosis where missing a disease is dangerous, which metric should be prioritized?',
            options: ['Precision', 'Recall (Sensitivity)', 'Accuracy only', 'Training Speed'],
            correctOptionIndex: 1,
            explanation: 'High recall minimizes False Negatives, ensuring fewer missed diagnoses.'
          }
        ]
      },
      {
        id: 'ai-04',
        title: 'Deep Learning & Neural Networks with PyTorch',
        order: 4,
        estimatedHours: 30,
        description: 'Feedforward neural networks, backpropagation, activation functions, and PyTorch training loops.',
        topics: ['Tensors & Autograd', 'Loss Functions & Optimizers (Adam)', 'Backpropagation Algorithm', 'PyTorch Dataset & DataLoader'],
        theoryMarkdown: `### Neural Networks\nConstruct multi-layer perceptrons with non-linear activations (ReLU, GELU) and backprop.`,
        keyTakeaways: ['Implement zero_grad, backward, step training cycle', 'Prevent vanishing gradients with modern activations'],
        quiz: [
          {
            id: 'q-ai-04',
            question: 'Why are activation functions (like ReLU) necessary in deep neural networks?',
            options: ['To speed up downloads', 'To introduce non-linearity so the network can learn complex patterns', 'To reduce data size', 'To round numbers to integers'],
            correctOptionIndex: 1,
            explanation: 'Without non-linear activations, multiple linear layers collapse into a single linear transformation.'
          }
        ]
      },
      {
        id: 'ai-05',
        title: 'Computer Vision & Convolutional Networks (CNNs)',
        order: 5,
        estimatedHours: 20,
        description: 'Image processing, convolution filters, pooling, ResNet architectures, and transfer learning.',
        topics: ['Convolution & Pooling Layers', 'Transfer Learning (ResNet, EfficientNet)', 'Data Augmentation', 'Object Detection Principles'],
        theoryMarkdown: `### Vision Systems\nExtract spatial features from image pixels using convolutional kernels.`,
        keyTakeaways: ['Leverage pre-trained weights with transfer learning', 'Augment image data with flips and rotations'],
        quiz: [
          {
            id: 'q-ai-05',
            question: 'What is the primary benefit of transfer learning in Computer Vision?',
            options: ['No code required', 'Uses feature representations learned from millions of images on small custom datasets', 'Eliminates all errors', 'Increases file resolution'],
            correctOptionIndex: 1,
            explanation: 'Transfer learning allows high accuracy on small datasets by reusing pre-trained vision features.'
          }
        ]
      },
      {
        id: 'ai-06',
        title: 'Natural Language Processing & Transformers',
        order: 6,
        estimatedHours: 25,
        description: 'Tokenization, word embeddings, self-attention mechanism, and Transformer architectures.',
        topics: ['BPE Tokenization & Embeddings', 'Self-Attention & Multi-Head Attention', 'BERT & GPT Architectures', 'Fine-Tuning on Custom Text'],
        theoryMarkdown: `### Modern NLP\nUnderstand the attention mechanism: Query, Key, and Value vector matrices.`,
        keyTakeaways: ['Compute attention weights with scaled dot-product', 'Use vector embeddings for semantic search'],
        quiz: [
          {
            id: 'q-ai-06',
            question: 'In the Transformer self-attention formula, what are the three core vector representations computed for each token?',
            options: ['Input, Output, Hidden', 'Query, Key, Value', 'Alpha, Beta, Gamma', 'Weight, Bias, Error'],
            correctOptionIndex: 1,
            explanation: 'Transformers compute attention using Query (Q), Key (K), and Value (V) projections.'
          }
        ]
      },
      {
        id: 'ai-07',
        title: 'Generative AI, RAG & LLM Application Engineering',
        order: 7,
        estimatedHours: 25,
        description: 'Prompt engineering, Retrieval-Augmented Generation (RAG), vector databases, and agent workflows.',
        topics: ['Prompt Design & Structured Outputs', 'Vector Embeddings & Cosine Similarity', 'RAG Architectures with Pinecone / Chroma', 'Tool Calling & AI Agents'],
        theoryMarkdown: `### Production GenAI\nGround large language models in private enterprise data using semantic retrieval.`,
        keyTakeaways: ['Chunk and embed documents into vector databases', 'Implement guardrails and structured JSON schemas'],
        quiz: [
          {
            id: 'q-ai-07',
            question: 'What is the primary purpose of Retrieval-Augmented Generation (RAG)?',
            options: ['To train a new model from scratch', 'To retrieve relevant factual context from a knowledge base and provide it to the LLM prompt', 'To compress image files', 'To translate code to assembly'],
            correctOptionIndex: 1,
            explanation: 'RAG reduces hallucinations and grounds responses by fetching real source documents.'
          }
        ]
      }
    ]
  },
  cyber_security: {
    id: 'cyber_security',
    name: 'Cyber Security & Ethical Hacking',
    tagline: 'Defend Networks, Detect Threats & Secure Digital Systems',
    icon: '🛡️',
    color: 'from-rose-600 to-red-600',
    accentColor: '#f43f5e',
    avgSalary: '$95,000 - $155,000',
    description:
      'Master network security protocols, vulnerability scanning, Linux system hardening, cryptography, web penetration testing (OWASP Top 10), and defensive incident response.',
    jobRoles: ['Security Analyst', 'Penetration Tester', 'SOC Analyst', 'Information Security Officer'],
    totalSkills: 6,
    skillsRoadmap: [
      {
        id: 'cs-01',
        title: 'Networking Protocols & Architecture',
        order: 1,
        estimatedHours: 16,
        description: 'OSI 7-layer model, TCP/IP handshake, DNS, DHCP, routing, firewalls, and packet analysis with Wireshark.',
        topics: ['TCP vs UDP & Handshake', 'Subnetting & CIDR Notation', 'DNS & HTTP/HTTPS Security', 'Wireshark Packet Inspection'],
        theoryMarkdown: `### Network Security Foundations\nEvery attack and defense moves through network packets. Understand TCP flags and DNS.`,
        keyTakeaways: ['Analyze packet streams for anomalous traffic', 'Configure stateful firewall rules'],
        quiz: [
          {
            id: 'q-cs-01',
            question: 'What three packets are exchanged during the standard TCP 3-way handshake?',
            options: ['SYN, ACK, FIN', 'SYN, SYN-ACK, ACK', 'HELLO, READY, GO', 'PING, PONG, ACK'],
            correctOptionIndex: 1,
            explanation: 'TCP establishes a connection via SYN (Client) -> SYN-ACK (Server) -> ACK (Client).'
          }
        ]
      },
      {
        id: 'cs-02',
        title: 'Linux Security & Bash Automation',
        order: 2,
        estimatedHours: 18,
        description: 'File permissions (chmod, chown), SSH hardening, system logging (syslog), and automated security scripting.',
        topics: ['Linux Permissions & SUID', 'SSH Key Authentication & Hardening', 'Audit Logs & journalctl', 'Bash Automation Scripts'],
        theoryMarkdown: `### Linux Hardening\nSecure servers by eliminating default accounts, enforcing least privilege, and monitoring auth logs.`,
        keyTakeaways: ['Disable root SSH password login', 'Find privilege escalation vectors with SUID audits'],
        quiz: [
          {
            id: 'q-cs-02',
            question: 'Which file permission setting allows users to execute a file with the permissions of the file owner?',
            options: ['Sticky Bit', 'SUID (Set User ID)', 'SGID', 'Read-Only'],
            correctOptionIndex: 1,
            explanation: 'SUID (e.g. chmod u+s) executes the file under the owner\'s permission level.'
          }
        ]
      },
      {
        id: 'cs-03',
        title: 'Applied Cryptography & Authentication',
        order: 3,
        estimatedHours: 16,
        description: 'Symmetric encryption (AES), asymmetric cryptography (RSA/ECC), hashing (SHA-256, bcrypt), and PKI/TLS.',
        topics: ['Symmetric vs Asymmetric', 'Cryptographic Hashes & Salt', 'TLS Handshake & Certificates', 'Multi-Factor Authentication (TOTP)'],
        theoryMarkdown: `### Cryptographic Principles\nNever store plain passwords. Use salted cryptographic key derivation functions like bcrypt or Argon2.`,
        keyTakeaways: ['Protect confidentiality with AES-GCM', 'Verify authenticity with digital signatures'],
        quiz: [
          {
            id: 'q-cs-03',
            question: 'Why should passwords always be hashed with a cryptographic salt?',
            options: ['To shorten the password', 'To prevent precomputed Rainbow Table attacks', 'To speed up database lookups', 'To make passwords readable'],
            correctOptionIndex: 1,
            explanation: 'Unique salts ensure identical passwords produce different hash outputs, defeating rainbow tables.'
          }
        ]
      },
      {
        id: 'cs-04',
        title: 'Web Application Security & OWASP Top 10',
        order: 4,
        estimatedHours: 24,
        description: 'Prevent SQL injection, Cross-Site Scripting (XSS), CSRF, SSRF, broken access control, and insecure direct object references.',
        topics: ['SQL Injection & Parameterization', 'Stored vs Reflected XSS', 'Cross-Site Request Forgery (CSRF)', 'Broken Object Level Auth (BOLA)'],
        theoryMarkdown: `### Application Defense\nSanitize all untrusted user input and enforce server-side authorization checks.`,
        keyTakeaways: ['Always use parameterized SQL queries', 'Escape and encode HTML outputs to prevent XSS'],
        quiz: [
          {
            id: 'q-cs-04',
            question: 'What is the most effective defense against SQL Injection vulnerabilities?',
            options: ['Hiding the database name', 'Parameterized queries / Prepared statements', 'Using longer passwords', 'Disabling JavaScript'],
            correctOptionIndex: 1,
            explanation: 'Parameterized queries treat user input strictly as data, never as executable SQL instructions.'
          }
        ]
      },
      {
        id: 'cs-05',
        title: 'Vulnerability Assessment & Penetration Testing',
        order: 5,
        estimatedHours: 22,
        description: 'Reconnaissance, Nmap port scanning, Burp Suite proxy testing, and ethical exploitation frameworks.',
        topics: ['Nmap Network Reconnaissance', 'Burp Suite Interception Proxy', 'Vulnerability Scanning with OpenVAS', 'Remediation Reporting'],
        theoryMarkdown: `### Offensive Assessment\nThink like an attacker to identify security vulnerabilities before malicious actors do.`,
        keyTakeaways: ['Conduct responsible testing with explicit authorization', 'Provide actionable remediation guidance in audit reports'],
        quiz: [
          {
            id: 'q-cs-05',
            question: 'Which tool is universally used to intercept, inspect, and modify HTTP requests during web penetration tests?',
            options: ['Burp Suite', 'Excel', 'Docker', 'Vite'],
            correctOptionIndex: 0,
            explanation: 'Burp Suite acts as an interception proxy for inspecting and altering client-server HTTP traffic.'
          }
        ]
      },
      {
        id: 'cs-06',
        title: 'Security Operations & Incident Response (SOC)',
        order: 6,
        estimatedHours: 20,
        description: 'SIEM log monitoring, threat hunting, malware containment, digital forensics, and incident response playbooks.',
        topics: ['SIEM Alert Triaging', 'Incident Response Lifecycle (NIST)', 'Root Cause Analysis', 'Threat Intelligence Feeds'],
        theoryMarkdown: `### Incident Response\nDetect intrusions rapidly, contain lateral movement, and eradicate threats.`,
        keyTakeaways: ['Follow structured NIST IR phases: Preparation, Detection, Containment, Eradication, Recovery', 'Preserve digital evidence chain of custody'],
        quiz: [
          {
            id: 'q-cs-06',
            question: 'What is the first operational priority immediately after confirming an active server compromise?',
            options: ['Delete all logs', 'Contain the incident to prevent lateral spread', 'Format the machine immediately', 'Email all users'],
            correctOptionIndex: 1,
            explanation: 'Containment (e.g. network isolation) prevents attackers from moving laterally while preserving forensic logs.'
          }
        ]
      }
    ]
  },
  cloud: {
    id: 'cloud',
    name: 'Cloud Computing & DevOps',
    tagline: 'Architect Resilient Cloud Infrastructure & CI/CD Pipelines',
    icon: '☁️',
    color: 'from-sky-600 to-blue-700',
    accentColor: '#0284c7',
    avgSalary: '$105,000 - $165,000',
    description:
      'Master Amazon Web Services (AWS), Google Cloud, Docker containerization, Kubernetes orchestration, Infrastructure as Code with Terraform, and automated CI/CD deployment.',
    jobRoles: ['Cloud Architect', 'DevOps Engineer', 'Site Reliability Engineer (SRE)', 'Platform Engineer'],
    totalSkills: 6,
    skillsRoadmap: [
      {
        id: 'cld-01',
        title: 'Cloud Architecture & Core Services (AWS)',
        order: 1,
        estimatedHours: 18,
        description: 'Compute (EC2, Lambda), Storage (S3), Networking (VPC, Subnets, Security Groups), and IAM policies.',
        topics: ['IAM Least Privilege Roles', 'Virtual Private Clouds (VPC)', 'EC2 Virtual Servers & S3 Storage', 'Serverless Functions (Lambda)'],
        theoryMarkdown: `### Cloud Computing Models\nDesign multi-tier cloud architectures with high availability and fault tolerance.`,
        keyTakeaways: ['Isolate resources in private subnets with NAT Gateways', 'Enforce least privilege with IAM policies'],
        quiz: [
          {
            id: 'q-cld-01',
            question: 'Which AWS service provides resizable virtual compute capacity in the cloud?',
            options: ['Amazon S3', 'Amazon EC2', 'Amazon RDS', 'Amazon Route 53'],
            correctOptionIndex: 1,
            explanation: 'Amazon Elastic Compute Cloud (EC2) provides virtual servers on demand.'
          }
        ]
      },
      {
        id: 'cld-02',
        title: 'Docker & Containerization',
        order: 2,
        estimatedHours: 16,
        description: 'Dockerfile authoring, multi-stage builds, container networking, volumes, and Docker Compose.',
        topics: ['Container vs Virtual Machine', 'Writing Efficient Dockerfiles', 'Multi-Stage Build Optimization', 'Docker Compose Services'],
        theoryMarkdown: `### Packaging Applications\nPackage application code with exact dependencies for reproducible environments everywhere.`,
        keyTakeaways: ['Minimize image sizes using multi-stage builds', 'Never store sensitive secrets in Docker images'],
        quiz: [
          {
            id: 'q-cld-02',
            question: 'What is the primary advantage of multi-stage Docker builds?',
            options: ['Runs multiple apps at once', 'Separates build tools from runtime, keeping production image size small', 'Encrypts source code', 'Skips compiling code'],
            correctOptionIndex: 1,
            explanation: 'Multi-stage builds leave compiler SDKs behind, shipping only production artifacts.'
          }
        ]
      },
      {
        id: 'cld-03',
        title: 'Kubernetes Container Orchestration',
        order: 3,
        estimatedHours: 24,
        description: 'Pods, Deployments, Services, Ingress controllers, ConfigMaps, and autoscaling across clusters.',
        topics: ['Pod & Deployment Manifests', 'Cluster Services & Ingress', 'Horizontal Pod Autoscaling (HPA)', 'Rolling Updates & Health Probes'],
        theoryMarkdown: `### Cluster Management\nOrchestrate thousands of microservice containers with self-healing and auto-scaling.`,
        keyTakeaways: ['Define liveness and readiness health checks', 'Perform zero-downtime rolling deployments'],
        quiz: [
          {
            id: 'q-cld-03',
            question: 'Which Kubernetes controller automatically scales the number of Pod replicas based on CPU utilization?',
            options: ['Kubelet', 'Horizontal Pod Autoscaler (HPA)', 'Ingress Controller', 'ConfigMap'],
            correctOptionIndex: 1,
            explanation: 'HPA dynamically scales Pod counts up or down based on observed metrics.'
          }
        ]
      },
      {
        id: 'cld-04',
        title: 'Infrastructure as Code (IaC) with Terraform',
        order: 4,
        estimatedHours: 20,
        description: 'Declarative cloud provisioning, Terraform state management, modules, and variable environments.',
        topics: ['HCL Syntax & Providers', 'Terraform State & Remote Backends', 'Modular Cloud Reusability', 'Plan & Apply Workflow'],
        theoryMarkdown: `### Declarative Infrastructure\nVersion-control cloud infrastructure just like application software.`,
        keyTakeaways: ['Lock state in remote backends (S3 + DynamoDB)', 'Review execution plans before applying cloud changes'],
        quiz: [
          {
            id: 'q-cld-04',
            question: 'Which Terraform command shows the proposed changes that will be made to your cloud infrastructure before execution?',
            options: ['terraform init', 'terraform plan', 'terraform apply --force', 'terraform test'],
            correctOptionIndex: 1,
            explanation: 'terraform plan computes differences and displays what resources will be created/updated/destroyed.'
          }
        ]
      },
      {
        id: 'cld-05',
        title: 'Automated CI/CD Pipelines (GitHub Actions)',
        order: 5,
        estimatedHours: 18,
        description: 'Build automated continuous integration, testing, Docker image publishing, and deployment workflows.',
        topics: ['Workflow Triggers & Jobs', 'Secret Management & Environments', 'Automated Test Execution', 'Blue/Green & Canary Deployments'],
        theoryMarkdown: `### Continuous Delivery\nAutomate the pathway from Git pull request to production release.`,
        keyTakeaways: ['Run lint and tests automatically on pull requests', 'Deploy to staging environments before production release'],
        quiz: [
          {
            id: 'q-cld-05',
            question: 'What is the purpose of a Continuous Integration (CI) pipeline?',
            options: ['To manually deploy code once a year', 'To automatically test and validate code changes on every commit', 'To write documentation', 'To replace developers'],
            correctOptionIndex: 1,
            explanation: 'CI automatically builds and tests code changes to catch bugs early.'
          }
        ]
      },
      {
        id: 'cld-06',
        title: 'Cloud Observability, SRE & Cost Optimization',
        order: 6,
        estimatedHours: 16,
        description: 'Metrics, logs, distributed tracing (Prometheus, Grafana), SLAs/SLOs, and AWS Cost Explorer.',
        topics: ['The 4 Golden Signals (Latency, Traffic, Errors, Saturation)', 'Prometheus & Grafana Dashboards', 'SLIs, SLOs & Error Budgets', 'FinOps & Cloud Cost Reduction'],
        theoryMarkdown: `### Reliability Engineering\nMonitor production health and optimize cloud spending.`,
        keyTakeaways: ['Monitor latency percentiles (p95, p99) instead of averages', 'Set up automated alerts for elevated error rates'],
        quiz: [
          {
            id: 'q-cld-06',
            question: 'In Site Reliability Engineering (SRE), what represents the agreed target level of service reliability?',
            options: ['SLI (Service Level Indicator)', 'SLO (Service Level Objective)', 'SLA only', 'RTO'],
            correctOptionIndex: 1,
            explanation: 'SLO is the target reliability goal (e.g. 99.9% uptime) that development and operations aim for.'
          }
        ]
      }
    ]
  },
  ui_ux: {
    id: 'ui_ux',
    name: 'UI/UX Design & Product Strategy',
    tagline: 'Design Intuitive User Experiences & High-Fidelity Interfaces',
    icon: '🎨',
    color: 'from-fuchsia-600 to-pink-600',
    accentColor: '#d946ef',
    avgSalary: '$80,000 - $135,000',
    description:
      'Master user research methodologies, information architecture, wireframing, interactive Figma prototyping, typography, design systems, and usability testing.',
    jobRoles: ['Product Designer', 'UI/UX Designer', 'Interaction Designer', 'Design Systems Specialist'],
    totalSkills: 6,
    skillsRoadmap: [
      {
        id: 'ux-01',
        title: 'User Research & Persona Development',
        order: 1,
        estimatedHours: 12,
        description: 'Conduct user interviews, surveys, empathy mapping, user journeys, and define target user personas.',
        topics: ['Qualitative vs Quantitative Research', 'Empathy Maps & User Personas', 'Journey Mapping', 'Problem Framing'],
        theoryMarkdown: `### User-Centered Discovery\nUncover real user pain points before designing visual solutions.`,
        keyTakeaways: ['Ask open-ended questions during discovery interviews', 'Map pain points along user journey timelines'],
        quiz: [
          {
            id: 'q-ux-01',
            question: 'What is the main goal of creating user personas in UX design?',
            options: ['To pick favorite colors', 'To represent target user segments, goals, and behavioral patterns', 'To write marketing copy', 'To eliminate testing'],
            correctOptionIndex: 1,
            explanation: 'Personas ground design decisions in real user needs, motivations, and pain points.'
          }
        ]
      },
      {
        id: 'ux-02',
        title: 'Information Architecture & Wireframing',
        order: 2,
        estimatedHours: 14,
        description: 'Card sorting, sitemap hierarchy, navigation patterns, and low-fidelity structural wireframes.',
        topics: ['Card Sorting Methods', 'Sitemap Architecture', 'Low-Fidelity Wireframes', 'Content Hierarchy'],
        theoryMarkdown: `### Structural Design\nOrganize content logically so users effortlessly find what they need.`,
        keyTakeaways: ['Group related workflows logically', 'Validate low-fidelity wireframes before polishing visual details'],
        quiz: [
          {
            id: 'q-ux-02',
            question: 'Which research method involves asking users to categorize topic cards to structure navigation menus?',
            options: ['A/B Testing', 'Card Sorting', 'Heatmap Analysis', 'Eyetracking'],
            correctOptionIndex: 1,
            explanation: 'Card sorting helps discover how target users naturally categorize information.'
          }
        ]
      },
      {
        id: 'ux-03',
        title: 'Figma Mastery: Components & Auto-Layout',
        order: 3,
        estimatedHours: 24,
        description: 'Auto-layout 5.0, responsive constraints, variants, interactive component states, and variables.',
        topics: ['Auto-Layout & Padding Rules', 'Component Variants & Properties', 'Figma Variables & Color Tokens', 'Smart Animate Prototyping'],
        theoryMarkdown: `### Industry Design Tooling\nBuild responsive, scalable UI components that mirror production frontend code.`,
        keyTakeaways: ['Use Auto-Layout for fluid container resizing', 'Leverage Figma variables for multi-theme design tokens'],
        quiz: [
          {
            id: 'q-ux-03',
            question: 'In Figma, which feature ensures child elements adjust their size and padding automatically when content changes?',
            options: ['Masking', 'Auto-Layout', 'Vector Networks', 'Flatten'],
            correctOptionIndex: 1,
            explanation: 'Auto-Layout dynamically adapts dimensions and spacing as content updates.'
          }
        ]
      },
      {
        id: 'ux-04',
        title: 'Design Systems & Visual Foundations',
        order: 4,
        estimatedHours: 20,
        description: 'Color tokens, typography scales, spacing grids (8pt system), elevation shadows, and accessible contrast.',
        topics: ['The 8-Point Grid System', 'Harmonious Color Palettes (60-30-10)', 'Typography Hierarchy & Scales', 'WCAG 2.1 AA Contrast Compliance'],
        theoryMarkdown: `### Design Tokens & Consistency\nCreate cohesive digital products with comprehensive design token specifications.`,
        keyTakeaways: ['Enforce WCAG 4.5:1 contrast ratios for body text', 'Align all margins and paddings to an 8pt spatial grid'],
        quiz: [
          {
            id: 'q-ux-04',
            question: 'What is the minimum WCAG AA contrast ratio required for standard body text against its background?',
            options: ['2:1', '3:1', '4.5:1', '7:1'],
            correctOptionIndex: 2,
            explanation: 'WCAG AA requires a 4.5:1 contrast ratio for normal body text to ensure accessibility.'
          }
        ]
      },
      {
        id: 'ux-05',
        title: 'Interactive Prototyping & Micro-Interactions',
        order: 5,
        estimatedHours: 16,
        description: 'State transitions, micro-animations, loading indicators, feedback loops, and realistic device previews.',
        topics: ['Easing Curves & Timing', 'Hover, Active, & Focus States', 'Micro-Animation Feedback', 'Interactive High-Fidelity Flow'],
        theoryMarkdown: `### Dynamic Interfaces\nMicro-interactions delight users and provide clear confirmation of system status.`,
        keyTakeaways: ['Keep UI animations between 150ms and 300ms for responsiveness', 'Provide immediate visual feedback on tap/click'],
        quiz: [
          {
            id: 'q-ux-05',
            question: 'What is the optimal duration range for standard UI micro-interactions and modal transitions?',
            options: ['10ms - 50ms', '150ms - 300ms', '1000ms - 2000ms', '5 seconds'],
            correctOptionIndex: 1,
            explanation: '150ms-300ms feels snappy to the human eye without causing cognitive delay.'
          }
        ]
      },
      {
        id: 'ux-06',
        title: 'Usability Testing & Design Handoff',
        order: 6,
        estimatedHours: 14,
        description: 'Conduct moderated usability tests, measure System Usability Scale (SUS), and prepare developer handoff specs.',
        topics: ['Usability Test Scripting', 'System Usability Scale (SUS)', 'Design Handoff & Redlines', 'Iterative Refinement'],
        theoryMarkdown: `### Validation & Delivery\nTest designs with actual users to catch friction points before engineering kickoff.`,
        keyTakeaways: ['Observe user behavior rather than just listening to opinions', 'Document edge cases and error states for developers'],
        quiz: [
          {
            id: 'q-ux-06',
            question: 'During a usability test, what should the facilitator do when a participant gets stuck?',
            options: ['Explain how to solve it immediately', 'Encourage them to think aloud without giving away the answer', 'Stop the test and fail them', 'Change the design in real-time'],
            correctOptionIndex: 1,
            explanation: 'Thinking aloud reveals the user\'s mental model and where design expectations diverge.'
          }
        ]
      }
    ]
  },
  data_science: {
    id: 'data_science',
    name: 'Data Science & Advanced Analytics',
    tagline: 'Extract Deep Insights & Statistical Models from Complex Data',
    icon: '🔬',
    color: 'from-emerald-600 to-cyan-600',
    accentColor: '#10b981',
    avgSalary: '$100,000 - $160,000',
    description:
      'Combine statistical inference, predictive machine learning, big data processing (PySpark), feature pipelines, and data-driven experimental design.',
    jobRoles: ['Data Scientist', 'Decision Scientist', 'Quantitative Analyst', 'Research Data Scientist'],
    totalSkills: 6,
    skillsRoadmap: [
      {
        id: 'ds-01',
        title: 'Statistical Inference & Probability Theory',
        order: 1,
        estimatedHours: 18,
        description: 'Probability distributions (Poisson, Normal, Binomial), Central Limit Theorem, and Bayesian inference.',
        topics: ['Probability Axioms & Bayes Rule', 'Central Limit Theorem', 'Confidence Intervals', 'Bootstrapping Methods'],
        theoryMarkdown: `### Mathematical Statistics\nQuantify uncertainty and infer population parameters from sample measurements.`,
        keyTakeaways: ['Understand Central Limit Theorem sample bounds', 'Use bootstrapping for non-parametric interval estimation'],
        quiz: [
          {
            id: 'q-ds-01',
            question: 'According to the Central Limit Theorem, the distribution of sample means approaches what shape as sample size increases?',
            options: ['Uniform', 'Normal / Gaussian', 'Exponential', 'Bimodal'],
            correctOptionIndex: 1,
            explanation: 'The CLT proves that sample means approximate a normal distribution for sufficiently large N.'
          }
        ]
      },
      {
        id: 'ds-02',
        title: 'Exploratory Data Analysis & Feature Engineering',
        order: 2,
        estimatedHours: 20,
        description: 'Multivariate data exploration, correlation analysis, dimensional scaling, and feature synthesis.',
        topics: ['Univariate & Bivariate EDA', 'Imputation Strategies', 'Log Transformations for Skew', 'Target Encoding vs One-Hot'],
        theoryMarkdown: `### Extracting Signal from Noise\nTransform messy input variables into predictive feature vectors.`,
        keyTakeaways: ['Handle skewed distributions with log/power transformations', 'Encode high-cardinality categorical features properly'],
        quiz: [
          {
            id: 'q-ds-02',
            question: 'Which transformation is commonly applied to right-skewed positive financial data to normalize its distribution?',
            options: ['Logarithmic Transformation', 'Squaring', 'Binarization', 'Multiplying by 100'],
            correctOptionIndex: 0,
            explanation: 'Log transforms compress large positive tails, pulling skewed distributions closer to normal.'
          }
        ]
      },
      {
        id: 'ds-03',
        title: 'Predictive Modeling & Cross-Validation Pipelines',
        order: 3,
        estimatedHours: 25,
        description: 'Scikit-learn pipelines, cross-validation strategies, regularized regression, and tree ensembles.',
        topics: ['K-Fold Cross-Validation', 'Lasso & Ridge Regularization', 'LightGBM & XGBoost', 'Model Interpretability (SHAP Values)'],
        theoryMarkdown: `### Robust Machine Learning\nBuild leakage-free pipelines that evaluate model performance reliably.`,
        keyTakeaways: ['Fit all scalers inside CV folds to prevent test leakage', 'Explain individual model predictions using SHAP values'],
        quiz: [
          {
            id: 'q-ds-03',
            question: 'Which regularization technique can drive feature coefficients completely to zero, performing automatic feature selection?',
            options: ['Ridge (L2)', 'Lasso (L1)', 'Dropout', 'Batch Normalization'],
            correctOptionIndex: 1,
            explanation: 'L1 Lasso regularization penalizes absolute coefficient values, shrinking irrelevant features to zero.'
          }
        ]
      },
      {
        id: 'ds-04',
        title: 'Experimental Design & A/B Testing',
        order: 4,
        estimatedHours: 16,
        description: 'Sample size determination, statistical power, randomized controlled trials, and metric definitions.',
        topics: ['Sample Size & Minimum Detectable Effect', 'Type I & Type II Errors', 'Two-Sample T-Tests & Chi-Square', 'Variance Reduction (CUPED)'],
        theoryMarkdown: `### Causal Inference\nDesign rigorous online experiments to measure the true causal impact of product interventions.`,
        keyTakeaways: ['Calculate required sample sizes before starting experiments', 'Avoid early stopping without alpha spending corrections'],
        quiz: [
          {
            id: 'q-ds-04',
            question: 'What is a Type I error in statistical hypothesis testing?',
            options: ['False Negative', 'False Positive (Rejecting a true null hypothesis)', 'Sample calculation error', 'Low statistical power'],
            correctOptionIndex: 1,
            explanation: 'Type I error occurs when you conclude an effect exists when it was actually random chance.'
          }
        ]
      },
      {
        id: 'ds-05',
        title: 'Big Data Processing with PySpark & SQL',
        order: 5,
        estimatedHours: 22,
        description: 'Distributed computing, Spark DataFrames, lazy evaluation, partitioning, and cloud data warehouses.',
        topics: ['Distributed Compute Concepts', 'PySpark Transformations & Actions', 'Partitioning & Shuffling Optimization', 'Data Lakehouse Architecture'],
        theoryMarkdown: `### Distributed Data at Scale\nProcess terabytes of log data across distributed compute clusters with Apache Spark.`,
        keyTakeaways: ['Differentiate lazy transformations from trigger actions', 'Optimize partitioning to avoid expensive data shuffling'],
        quiz: [
          {
            id: 'q-ds-05',
            question: 'In Apache Spark, which of the following is an "Action" that triggers actual computation across the cluster?',
            options: ['df.filter()', 'df.select()', 'df.count()', 'df.withColumn()'],
            correctOptionIndex: 2,
            explanation: 'count(), collect(), and show() are actions that trigger the DAG execution plan.'
          }
        ]
      },
      {
        id: 'ds-06',
        title: 'Data Science Capstone & Business Communication',
        order: 6,
        estimatedHours: 20,
        description: 'End-to-end data product development, translating findings into ROI metrics, and executive presentations.',
        topics: ['End-to-End Problem Formulation', 'Translating Model Accuracy to Revenue/Cost', 'Interactive Dashboard Storytelling', 'Technical Whitepaper Writing'],
        theoryMarkdown: `### Executive Impact\nThe best model is worthless if stakeholders do not adopt its recommendations. Learn to articulate business value.`,
        keyTakeaways: ['Frame findings around business KPIs (churn reduction, conversion lift)', 'Document assumptions, risks, and monitoring plans'],
        quiz: [
          {
            id: 'q-ds-06',
            question: 'When presenting machine learning results to non-technical executives, what should you lead with?',
            options: ['The mathematical derivative formula', 'The business impact, key recommendation, and expected ROI', 'The neural network layer count', 'The raw CSV log'],
            correctOptionIndex: 1,
            explanation: 'Executive communication begins with the bottom-line business value and actionable takeaways.'
          }
        ]
      }
    ]
  }
}
